version: '2.1'

#create a network and add our services into this network:
networks:
  test-network:

services:
  # webserver
  # database
  spring-boot:
    image: psysanta/demo
    build: .
    ports:
      - 3000:8080
    restart:
      always
    # depends_on:
    #   db:
    #     condition: service_healthy
    # networks:
    #   - test-network

  # dbms:
  #   image: opavlova/db-mysql:5.7-test
  #   container_name: db
  #   ports:
  #     - "13306:3306"
  #   healthcheck:
  #         test: ["CMD", "mysql", "-h", "localhost", "-P", "3306", "-u", "root", "--password=root", "-e", "select 1", "DOCKERDB"]
  #         interval: 1s
  #         timeout: 3s
  #         retries: 30
  #   networks:
  #     - test-network